### ISSUE TITLE
disable padding.

### ISSUE THREAD

**Issue by livc** [yzhangcs/biaffine-parser#20]
Hi, is there a fast way to disable padding to make sure all sentences in a batch have the same length?
Thanks.

**Comment by livc** [comment]
I set `k = len(d)` in `parser/utils/alg.py` to make sure no padding.

**Comment by zysite** [comment]
> I set `k = len(d)` in `parser/utils/alg.py` to make sure no padding.

No, this operation can't ensure no padding, since there is no guarantee that all sentences in a batch are in the same bucket.

**Comment by livc** [comment]
So any suggestions?

**Comment by zysite** [comment]
Since sentences are variable-length, there's no way to totally avoid the padding.
Actually, using kmeans algorithm can guarantee that all the sentences in a batch are roughly the same length.
